// <auto-generated />
namespace XPW.Admin.XPWAdminContextMigration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PagePermission_07252019_2106 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PagePermission_07252019_2106));
        
        string IMigrationMetadata.Id
        {
            get { return "201907251306549_PagePermission_07252019_2106"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
