// <auto-generated />
namespace XPW.CommonData.XPWCommonDataContextMigration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NewTable_072522019_0602 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewTable_072522019_0602));
        
        string IMigrationMetadata.Id
        {
            get { return "201907242207467_NewTable_072522019_0602"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
