// <auto-generated />
namespace XPW.CommonData.XPWExternalMigration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class XPWExternalInitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(XPWExternalInitial));
        
        string IMigrationMetadata.Id
        {
            get { return "201907251340536_XPWExternal.Initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
